<?php

/**
 * Tuxxedo Engine
 *
 * This file is part of the Tuxxedo Engine framework and is licensed under
 * the MIT license.
 *
 * Copyright (C) 2026 Kalle Sommer Nielsen <kalle@php.net>
 */

declare(strict_types=1);

namespace Support\Model;

class PgsqlModelSchemaProvider implements ModelSchemaProvider
{
    public function countriesSchemaSql(): string
    {
        return 'CREATE TABLE countries (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'name VARCHAR(255) NOT NULL, ' .
            'code VARCHAR(2) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function usersSchemaSql(): string
    {
        return 'CREATE TABLE users (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'name VARCHAR(255) NOT NULL, ' .
            'email VARCHAR(255) NOT NULL, ' .
            '"isActive" SMALLINT NOT NULL DEFAULT 1, ' .
            '"postCount" INTEGER NOT NULL DEFAULT 0, ' .
            'score DOUBLE PRECISION NOT NULL DEFAULT 0, ' .
            'country_id INTEGER NULL, ' .
            '"lastLoginAt" VARCHAR(64) NULL, ' .
            '"createdAt" VARCHAR(64) NULL, ' .
            '"updatedAt" VARCHAR(64) NULL' .
            ')';
    }

    public function profilesSchemaSql(): string
    {
        return 'CREATE TABLE profiles (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'user_id INTEGER NOT NULL, ' .
            'bio TEXT NOT NULL DEFAULT \'\', ' .
            'avatar BYTEA NULL, ' .
            'settings TEXT NULL, ' .
            '"birthDate" VARCHAR(64) NULL' .
            ')';
    }

    public function postsSchemaSql(): string
    {
        return 'CREATE TABLE posts (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'user_id INTEGER NOT NULL, ' .
            'title VARCHAR(255) NOT NULL, ' .
            'body TEXT NOT NULL DEFAULT \'\', ' .
            'status VARCHAR(32) NOT NULL DEFAULT \'draft\', ' .
            '"publishedAt" VARCHAR(64) NULL, ' .
            '"viewCount" BIGINT NOT NULL DEFAULT 0, ' .
            'rating NUMERIC(10, 2) NOT NULL DEFAULT 0.00' .
            ')';
    }

    public function commentsSchemaSql(): string
    {
        return 'CREATE TABLE comments (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'post_id INTEGER NOT NULL, ' .
            'user_id INTEGER NOT NULL, ' .
            'body TEXT NOT NULL DEFAULT \'\', ' .
            '"createdAt" VARCHAR(64) NULL, ' .
            '"deletedAt" VARCHAR(64) NULL' .
            ')';
    }

    public function tagsSchemaSql(): string
    {
        return 'CREATE TABLE tags (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'slug VARCHAR(255) NOT NULL, ' .
            'name VARCHAR(255) NOT NULL, ' .
            'category VARCHAR(255) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function rolesSchemaSql(): string
    {
        return 'CREATE TABLE roles (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            '"key" VARCHAR(20) NOT NULL, ' .
            'label VARCHAR(100) NOT NULL, ' .
            '"sortOrder" SMALLINT NOT NULL DEFAULT 0, ' .
            '"startsAt" VARCHAR(64) NULL' .
            ')';
    }

    public function categoriesSchemaSql(): string
    {
        return 'CREATE TABLE categories (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'parent_id INTEGER NULL, ' .
            'name VARCHAR(100) NOT NULL, ' .
            'depth SMALLINT NOT NULL DEFAULT 0' .
            ')';
    }

    public function postTagPivotSchemaSql(): string
    {
        return 'CREATE TABLE post_tag (' .
            'post_id INTEGER NOT NULL, ' .
            'tag_id INTEGER NOT NULL, ' .
            'PRIMARY KEY (post_id, tag_id)' .
            ')';
    }

    public function userRolePivotSchemaSql(): string
    {
        return 'CREATE TABLE user_role (' .
            'user_id INTEGER NOT NULL, ' .
            'role_id INTEGER NOT NULL, ' .
            'PRIMARY KEY (user_id, role_id)' .
            ')';
    }

    public function sentinelsSchemaSql(): string
    {
        return 'CREATE TABLE sentinels (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'state VARCHAR(64) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function cascadeGroupsSchemaSql(): string
    {
        return 'CREATE TABLE cascade_groups (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'name VARCHAR(255) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function cascadeChildrenSchemaSql(): string
    {
        return 'CREATE TABLE cascade_children (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'auto_group_id INTEGER NULL, ' .
            'restrict_group_id INTEGER NULL, ' .
            'nullable_group_id INTEGER NULL, ' .
            'noaction_group_id INTEGER NULL, ' .
            'label VARCHAR(255) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function cascadeHasOneChildrenSchemaSql(): string
    {
        return 'CREATE TABLE cascade_hasone_children (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'group_id INTEGER NOT NULL, ' .
            'label VARCHAR(255) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function cascadeHasOneRestrictChildrenSchemaSql(): string
    {
        return 'CREATE TABLE cascade_hasone_restrict_children (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'group_id INTEGER NOT NULL, ' .
            'label VARCHAR(255) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function cascadeTagsSchemaSql(): string
    {
        return 'CREATE TABLE cascade_tags (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'name VARCHAR(255) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function cascadeGroupTagPivotSchemaSql(): string
    {
        return 'CREATE TABLE cascade_group_tag (' .
            'group_id INTEGER NOT NULL, ' .
            'tag_id INTEGER NOT NULL, ' .
            'PRIMARY KEY (group_id, tag_id)' .
            ')';
    }

    public function readonlyRecordsSchemaSql(): string
    {
        return 'CREATE TABLE readonly_records (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'name VARCHAR(255) NOT NULL' .
            ')';
    }

    public function settingsSchemaSql(): string
    {
        return 'CREATE TABLE settings (' .
            'scope VARCHAR(64) NOT NULL, ' .
            'name VARCHAR(64) NOT NULL, ' .
            'value TEXT NOT NULL DEFAULT \'\', ' .
            'PRIMARY KEY (scope, name)' .
            ')';
    }

    public function bulkParentsSchemaSql(): string
    {
        return 'CREATE TABLE bulk_parents (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'name VARCHAR(255) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function bulkChildrenSchemaSql(): string
    {
        return 'CREATE TABLE bulk_children (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'parent_id INTEGER NOT NULL, ' .
            'label VARCHAR(255) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function orphanParentsSchemaSql(): string
    {
        return 'CREATE TABLE orphan_parents (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'name VARCHAR(255) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function orphanChildrenSchemaSql(): string
    {
        return 'CREATE TABLE orphan_children (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'parent_id INTEGER NULL, ' .
            'label VARCHAR(255) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function cascadeBelongsToParentsSchemaSql(): string
    {
        return 'CREATE TABLE cascade_bt_parents (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'name VARCHAR(255) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function cascadeBelongsToChildrenSchemaSql(): string
    {
        return 'CREATE TABLE cascade_bt_children (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'parent_id INTEGER NULL, ' .
            'label VARCHAR(255) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function strictOwnersSchemaSql(): string
    {
        return 'CREATE TABLE strict_owners (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'name VARCHAR(255) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function strictProfilesSchemaSql(): string
    {
        return 'CREATE TABLE strict_profiles (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'owner_id INTEGER NOT NULL, ' .
            'handle VARCHAR(255) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function strictChildrenSchemaSql(): string
    {
        return 'CREATE TABLE strict_children (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'owner_id INTEGER NULL, ' .
            'label VARCHAR(255) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function regionsSchemaSql(): string
    {
        return 'CREATE TABLE regions (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'name VARCHAR(255) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function branchesSchemaSql(): string
    {
        return 'CREATE TABLE branches (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'region_id INTEGER NOT NULL, ' .
            'warehouse_id INTEGER NOT NULL' .
            ')';
    }

    public function warehousesSchemaSql(): string
    {
        return 'CREATE TABLE warehouses (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'name VARCHAR(255) NOT NULL DEFAULT \'\'' .
            ')';
    }

    public function nullableThroughOwnersSchemaSql(): string
    {
        return 'CREATE TABLE nullable_through_owners (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'nullable_ref_id INTEGER NULL' .
            ')';
    }

    public function strictThroughOwnersSchemaSql(): string
    {
        return 'CREATE TABLE strict_through_owners (' .
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' .
            'nullable_ref_id INTEGER NULL' .
            ')';
    }
}
