name: PHP CS Fixer

on: [ push ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install PHP-CS-Fixer
        run: composer global require friendsofphp/php-cs-fixer

      - name: Run PHP-CS-Fixer
        run: ~/.composer/vendor/bin/php-cs-fixer check --verbose --config=.php-cs-fixer.php --allow-risky=yes --diff
