name: PHPUnit

on: [ push, pull_request ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_ROOT_HOST: '%'
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: '12345'
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      TUXXEDO_TEST_MYSQL_HOST: '127.0.0.1'
      TUXXEDO_TEST_MYSQL_PORT: '3306'
      TUXXEDO_TEST_MYSQL_USER: 'root'
      TUXXEDO_TEST_MYSQL_PASS: ''
      TUXXEDO_TEST_MYSQL_ADMIN_DATABASE: 'mysql'
      TUXXEDO_TEST_MYSQL_DATABASE_PREFIX: 'tuxxedo_test'
      TUXXEDO_TEST_MYSQL_CHARSET: 'utf8mb4'
      TUXXEDO_TEST_MYSQL_TIMEOUT: '5'
      TUXXEDO_TEST_PGSQL_HOST: '127.0.0.1'
      TUXXEDO_TEST_PGSQL_PORT: '5432'
      TUXXEDO_TEST_PGSQL_USER: 'postgres'
      TUXXEDO_TEST_PGSQL_PASS: '12345'
      TUXXEDO_TEST_PGSQL_ADMIN_DATABASE: 'postgres'
      TUXXEDO_TEST_PGSQL_DATABASE_PREFIX: 'tuxxedo_test'
      TUXXEDO_TEST_PGSQL_CHARSET: 'UTF8'
      TUXXEDO_TEST_PGSQL_TIMEOUT: '5'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: xdebug
          extensions: filter, mbstring, mysqli, openssl, pdo, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, session, sodium, sqlite3, fileinfo

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPUnit with coverage
        run: vendor/bin/paratest --processes=auto --coverage-clover=coverage.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v5
        with:
          name: coverage-report
          path: coverage.xml
